<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>TeamsGenerator</RootNamespace>
    <AssemblyName>TeamsGenerator</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CLI\CopyAndExit.cs" />
    <Compile Remove="ConsolePlayground.cs" />
    <Compile Remove="DataReaders\ExcelReader.cs" />
    <Compile Remove="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Algos\PositionsAlgo\players.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Algos\AiAlgo\players.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Algos\BackAndForthAlgo\players.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Algos\SkillWiseAlgo\players.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
